import { Heart, LogOut, MapPin, Package, UserRound } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useFavorites } from '../contexts/FavoritesContext';
import { listOrders } from '../services/orders';

export function AccountPage() {
  const { user, logout } = useAuth();
  const { favoriteIds } = useFavorites();
  const orders = user ? listOrders(user.id) : [];
  const navigate = useNavigate();
  if (!user) return null;
  function handleLogout() { logout(); navigate('/login', { replace: true }); }
  return <main className="mx-auto max-w-6xl px-5 py-12 sm:px-10 lg:px-16 lg:py-20"><div className="flex flex-col gap-6 border-b border-white/10 pb-10 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Monarch / Área pessoal</p><h1 className="section-title mt-4">Minha conta</h1><p className="mt-4 text-sm text-neutral-500">Olá, {user.name.split(' ')[0]}. Gerencie sua experiência Monarch.</p></div><button type="button" onClick={handleLogout} className="flex items-center gap-2 self-start text-[10px] uppercase tracking-[0.16em] text-neutral-500 transition hover:text-white sm:self-auto"><LogOut size={15} /> Sair</button></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><section className="border border-white/10 bg-[#161616] p-6"><UserRound size={18} className="text-[#c2ae8b]" /><p className="eyebrow mt-6">Dados pessoais</p><h2 className="mt-3 text-xl">{user.name}</h2><p className="mt-2 break-all text-sm text-neutral-500">{user.email}</p><p className="mt-6 text-xs leading-5 text-neutral-600">Seus dados estão salvos apenas neste navegador enquanto o sistema real não é integrado.</p></section><section className="border border-white/10 bg-[#161616] p-6"><MapPin size={18} className="text-[#c2ae8b]" /><p className="eyebrow mt-6">Endereços</p><h2 className="mt-3 text-xl">Sua entrega</h2><p className="mt-2 text-sm text-neutral-500">Nenhum endereço salvo.</p><span className="mt-6 block text-xs text-neutral-600">Cadastro de endereços em breve.</span></section><section className="border border-white/10 bg-[#161616] p-6"><Package size={18} className="text-[#c2ae8b]" /><p className="eyebrow mt-6">Pedidos</p><h2 className="mt-3 text-xl">{orders.length ? `${orders.length} ${orders.length === 1 ? 'pedido' : 'pedidos'}` : 'Histórico'}</h2><p className="mt-2 text-sm text-neutral-500">{orders.length ? 'Acompanhe seus pedidos registrados.' : 'Nenhum pedido realizado.'}</p>{orders.length ? <Link to="/pedidos" className="mt-6 inline-block text-[10px] uppercase tracking-[0.16em] text-[#c2ae8b] hover:text-white">Ver meus pedidos</Link> : <span className="mt-6 block text-xs text-neutral-600">Seus pedidos aparecerão aqui.</span>}</section></div><section className="mt-5 border border-white/10 bg-[#161616] p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-3"><Heart size={18} className="text-[#c2ae8b]" /><p className="eyebrow">Sua curadoria</p></div><h2 className="mt-4 text-2xl">Favoritos salvos</h2><p className="mt-2 text-sm text-neutral-500">Você tem {favoriteIds.length} {favoriteIds.length === 1 ? 'item salvo' : 'itens salvos'} na sua lista.</p></div><Link to="/favoritos" className="button-secondary">Ver favoritos</Link></div></section><p className="mt-8 text-xs leading-5 text-neutral-600">Protótipo de conta local. A autenticação real, pedidos e endereços serão substituídos por integrações de backend em uma próxima etapa.</p></main>;
}
