import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useCart } from '../contexts/CartContext';
import { getProductImages } from '../data/media';
import type { CartItem } from '../types/cart';
import { formatBRL } from '../utils/currency';

function CartItemRow({ item }: { item: CartItem }) {
  const { updateItemQuantity, removeItem } = useCart();
  const image = getProductImages(item.product)[0];
  const variation = [item.size && `Tamanho ${item.size}`, item.color && `Cor ${item.color}`].filter(Boolean).join(' · ');
  const updateQuantity = (quantity: number) => updateItemQuantity(item.product.id, item.size, item.color, quantity);

  return <article className="grid gap-4 border-b border-white/10 py-6 sm:grid-cols-[104px_1fr_auto] sm:items-center sm:gap-5"><div className="aspect-[4/5] w-24 overflow-hidden bg-[#1d1d1d]">{image ? <img src={image} alt={item.product.name} className="h-full w-full object-cover" /> : <div className="h-full w-full" aria-label={`Imagem de ${item.product.name} indisponível`} />}</div><div className="min-w-0"><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-neutral-500">{item.product.category.replace('-', ' ')}</p><Link to={`/produto/${item.product.slug}`} className="mt-2 block text-base font-medium text-white hover:text-[#c2ae8b]">{item.product.name}</Link>{variation && <p className="mt-2 text-xs text-neutral-500">{variation}</p>}<p className="mt-3 text-sm text-neutral-300">{formatBRL(item.product.price)}</p></div><div className="flex items-center justify-between gap-4 sm:flex-col sm:items-end"><div className="flex h-11 items-center border border-white/15"><button type="button" aria-label={`Diminuir quantidade de ${item.product.name}`} disabled={item.quantity <= 1} onClick={() => updateQuantity(item.quantity - 1)} className="grid h-full w-10 place-items-center text-neutral-400 transition hover:text-white disabled:opacity-30"><Minus size={14} /></button><input aria-label={`Quantidade de ${item.product.name}`} type="number" min="1" max={item.product.stock} value={item.quantity} onChange={(event) => { const next = Number(event.target.value); if (Number.isFinite(next) && next >= 1) updateQuantity(Math.min(item.product.stock, Math.floor(next))); }} className="h-full w-10 bg-transparent text-center text-sm text-white outline-none [appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none" /><button type="button" aria-label={`Aumentar quantidade de ${item.product.name}`} disabled={item.quantity >= item.product.stock} onClick={() => updateQuantity(item.quantity + 1)} className="grid h-full w-10 place-items-center text-neutral-400 transition hover:text-white disabled:opacity-30"><Plus size={14} /></button></div><div className="flex items-center gap-4"><strong className="text-sm text-white">{formatBRL(item.product.price * item.quantity)}</strong><button type="button" aria-label={`Remover ${item.product.name} do carrinho`} onClick={() => removeItem(item.product.id, item.size, item.color)} className="text-neutral-500 transition hover:text-white"><Trash2 size={15} /></button></div></div></article>;
}

function CartSummary({ subtotal }: { subtotal: number }) {
  return <aside className="h-fit border border-white/10 bg-[#161616] p-6 sm:p-8"><p className="eyebrow">Resumo da compra</p><h2 className="mt-3 text-2xl font-medium tracking-[-0.03em]">Sua seleção</h2><div className="mt-8 space-y-4 border-b border-white/10 pb-6 text-sm"><div className="flex justify-between gap-4 text-neutral-400"><span>Subtotal</span><span className="text-white">{formatBRL(subtotal)}</span></div><div className="flex justify-between gap-4 text-neutral-400"><span>Frete</span><span className="text-white">A calcular</span></div></div><div className="mt-6 flex justify-between gap-4 text-base"><strong>Total</strong><strong>{formatBRL(subtotal)}</strong></div><Link to="/checkout" className="button-primary mt-8 w-full"><ShoppingBag size={16} /> Finalizar compra</Link><p className="mt-4 text-center text-[10px] leading-5 text-neutral-600">O pagamento será preparado na próxima etapa.</p></aside>;
}

function EmptyCart() {
  return <section className="border-y border-white/10 py-24 text-center"><ShoppingBag size={27} className="mx-auto text-neutral-600" /><h2 className="mt-6 text-2xl font-medium tracking-[-0.03em]">Seu carrinho está vazio</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-neutral-500">Explore a curadoria Monarch e encontre a próxima peça do seu uniforme.</p><Link to="/catalogo" className="button-primary mt-8">Explorar produtos</Link></section>;
}

export function CartPage() {
  const { items, clearCart } = useCart();
  const subtotal = items.reduce((sum, item) => sum + item.product.price * item.quantity, 0);
  return <main className="mx-auto max-w-[1440px] px-5 py-14 sm:px-10 lg:px-16 lg:py-20"><header className="max-w-3xl"><p className="eyebrow">Monarch / Selection</p><h1 className="section-title mt-4">Carrinho</h1><p className="mt-5 max-w-xl text-sm leading-6 text-neutral-400 sm:text-base">Revise suas escolhas antes de seguir para a próxima etapa.</p></header>{items.length === 0 ? <div className="mt-12"><EmptyCart /></div> : <div className="mt-12 grid gap-12 lg:grid-cols-[1fr_360px] lg:items-start"><section aria-label="Itens do carrinho"><div className="flex items-center justify-between border-y border-white/10 py-4"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-neutral-500">{items.length} {items.length === 1 ? 'item' : 'itens'}</p><button type="button" onClick={clearCart} className="text-[10px] uppercase tracking-[0.16em] text-neutral-500 transition hover:text-white">Limpar carrinho</button></div>{items.map((item) => <CartItemRow key={`${item.product.id}-${item.size ?? ''}-${item.color ?? ''}`} item={item} />)}</section><CartSummary subtotal={subtotal} /></div>}<div className="mt-16 border-t border-white/10 pt-5"><Link to="/catalogo" className="text-[10px] uppercase tracking-[0.16em] text-neutral-500 transition hover:text-white">Continuar comprando</Link></div></main>;
}
