import { ArrowRight, Package } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { listOrders } from '../services/orders';
import { formatBRL } from '../utils/currency';

const statusLabels = { received: 'Pedido recebido', confirmed: 'Confirmado', processing: 'Em preparação', shipped: 'Enviado', delivered: 'Entregue', cancelled: 'Cancelado' } as const;

export function OrdersPage() {
  const { user } = useAuth();
  if (!user) return null;
  const orders = listOrders(user.id);
  return <main className="mx-auto max-w-6xl px-5 py-12 sm:px-10 lg:px-16 lg:py-20"><p className="eyebrow">Monarch / Área pessoal</p><div className="mt-4 flex flex-col gap-5 border-b border-white/10 pb-10 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="section-title">Meus pedidos</h1><p className="mt-4 text-sm text-neutral-500">Acompanhe os pedidos registrados nesta sessão local.</p></div><Link to="/minha-conta" className="text-[10px] uppercase tracking-[0.16em] text-neutral-500 hover:text-white">Voltar à conta</Link></div>{orders.length === 0 ? <div className="flex flex-col items-center border-b border-white/10 py-20 text-center"><Package size={28} className="text-neutral-600" /><h2 className="mt-6 text-2xl text-white">Nenhum pedido ainda</h2><p className="mt-3 max-w-sm text-sm leading-6 text-neutral-500">Quando você finalizar uma compra, ela aparecerá aqui.</p><Link to="/catalogo" className="button-primary mt-8">Explorar catálogo</Link></div> : <div className="mt-10 space-y-4">{orders.map((order) => <article key={order.id} className="border border-white/10 bg-[#161616] p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 gap-4"><div className="h-20 w-16 shrink-0 overflow-hidden bg-[#222]">{order.items[0]?.image ? <img src={order.items[0].image} alt={order.items[0].name} className="h-full w-full object-cover" /> : <div className="h-full w-full" />}</div><div><p className="eyebrow">{order.number}</p><h2 className="mt-2 text-lg text-white">{order.items.length === 1 ? order.items[0].name : `${order.items.length} produtos`}</h2><p className="mt-2 text-xs text-neutral-500">{new Date(order.createdAt).toLocaleDateString('pt-BR')} · {order.items.reduce((sum, item) => sum + item.quantity, 0)} {order.items.reduce((sum, item) => sum + item.quantity, 0) === 1 ? 'item' : 'itens'}</p></div></div><div className="flex items-center justify-between gap-5 sm:justify-end"><div className="text-left sm:text-right"><p className="text-[10px] uppercase tracking-[0.14em] text-[#c2ae8b]">{statusLabels[order.status]}</p><p className="mt-2 text-sm text-white">{formatBRL(order.total)}</p></div><Link to={`/pedidos/${order.id}`} aria-label={`Ver detalhes do pedido ${order.number}`} className="grid h-10 w-10 place-items-center border border-white/15 text-white hover:border-white"><ArrowRight size={16} /></Link></div></div></article>)}</div>}</main>;
}
