import { Check } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { getOrder } from '../services/orders';
import { formatBRL } from '../utils/currency';

export function OrderConfirmationPage() {
  const { user } = useAuth();
  const [params] = useSearchParams();
  const order = user && params.get('pedido') ? getOrder(user.id, params.get('pedido') as string) : null;
  if (!order) return <main className="mx-auto flex min-h-[65vh] max-w-3xl flex-col items-center justify-center px-5 py-20 text-center"><p className="eyebrow">Monarch / Pedido</p><h1 className="section-title mt-4">Pedido não encontrado</h1><p className="mt-5 max-w-md text-sm leading-6 text-neutral-500">Não encontramos esta confirmação para a sessão atual.</p><Link to="/catalogo" className="button-primary mt-8">Continuar comprando</Link></main>;
  return <main className="mx-auto max-w-4xl px-5 py-12 sm:px-10 lg:py-20"><div className="border border-white/10 bg-[#161616] p-6 sm:p-10"><div className="flex flex-col items-start gap-6 border-b border-white/10 pb-8 sm:flex-row sm:items-center"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-[#c2ae8b] text-black"><Check size={24} /></div><div><p className="eyebrow">Monarch / Pedido recebido</p><h1 className="section-title mt-3 text-4xl">Tudo certo por aqui.</h1><p className="mt-3 text-sm text-neutral-500">Seu pedido foi registrado localmente no protótipo.</p></div></div><div className="grid gap-5 border-b border-white/10 py-8 sm:grid-cols-3"><div><p className="eyebrow">Número</p><p className="mt-2 text-sm text-white">{order.number}</p></div><div><p className="eyebrow">Data</p><p className="mt-2 text-sm text-white">{new Date(order.createdAt).toLocaleDateString('pt-BR')}</p></div><div><p className="eyebrow">Total</p><p className="mt-2 text-sm text-white">{formatBRL(order.total)}</p></div></div><div className="py-8"><p className="eyebrow">Resumo dos produtos</p><div className="mt-6 space-y-4">{order.items.map((item) => <div key={`${item.productId}-${item.size ?? ''}-${item.color ?? ''}`} className="flex gap-4"><div className="h-20 w-16 shrink-0 overflow-hidden bg-[#222]">{item.image ? <img src={item.image} alt={item.name} className="h-full w-full object-cover" /> : <div className="h-full w-full" />}</div><div className="flex-1"><p className="text-sm text-white">{item.name}</p><p className="mt-1 text-xs text-neutral-500">{[item.size && `Tam. ${item.size}`, item.color, `Qtd. ${item.quantity}`].filter(Boolean).join(' · ')}</p></div><p className="text-sm text-white">{formatBRL(item.subtotal)}</p></div>)}</div></div><div className="flex flex-col gap-3 border-t border-white/10 pt-8 sm:flex-row"><Link to="/pedidos" className="button-primary">Meus pedidos</Link><Link to="/catalogo" className="button-secondary">Continuar comprando</Link></div></div></main>;
}
